plugin: aws_ec2
regions:
  - us-east-1
keyed_groups:
  - key: tags.Type
    prefix: type
  - key: instance_type
    prefix: instance_type
  - key: placement.availability_zone
    prefix: az
hostnames:
  - ip-address
compose:
  ansible_host: public_ip_address
filters:
  tag:Type: minecraft-server
  instance-state-name: running
