---
- name: Setup Minecraft Server
  hosts: localhost
  gather_facts: false
  vars:
    target_ip: "{{ target_ip | default('') }}"
  tasks:
    - name: Add target host to inventory
      add_host:
        name: minecraft_server
        ansible_host: "{{ target_ip }}"
        ansible_user: ec2-user
        ansible_ssh_private_key_file: ~/.ssh/aws-academy-key.pem
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      when: target_ip != ""

- name: Configure Minecraft Server
  hosts: minecraft_server
  become: yes
  gather_facts: yes
  vars:
    minecraft_version: "1.20.4"
    minecraft_port: 25565
    minecraft_max_players: 20
    minecraft_difficulty: "normal"
    minecraft_gamemode: "survival"
    minecraft_motd: "Acme Corp Minecraft Server - Welcome!"
    minecraft_user: minecraft
    minecraft_dir: /opt/minecraft/server
    java_heap_size: 1G
    enable_rcon: true
    rcon_port: 25575
    rcon_password: "{{ ansible_date_time.epoch | hash('md5') }}"

  tasks:
    - name: Wait for system to be ready
      wait_for_connection:
        timeout: 300

    - name: Gather facts
      setup:

    - name: Install required packages
      yum:
        name:
          - java-17-amazon-corretto-headless
          - wget
          - curl
          - screen
          - htop
          - nano
          - nc
        state: present

    - name: Create minecraft user
      user:
        name: "{{ minecraft_user }}"
        shell: /bin/bash
        home: /opt/minecraft
        create_home: yes
        system: yes

    - name: Create minecraft directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_user }}"
        mode: '0755'
      loop:
        - "{{ minecraft_dir }}"
        - /opt/minecraft/backups
        - /opt/minecraft/logs
        - /opt/minecraft/scripts

    - name: Download Minecraft server
      get_url:
        url: "https://piston-data.mojang.com/v1/objects/8f3112a1049751cc472ec13e397eade5336ca7ae/server.jar"
        dest: "{{ minecraft_dir }}/minecraft_server.jar"
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_user }}"
        mode: '0644'
      notify: restart minecraft

    - name: Create server.properties
      template:
        src: server.properties.j2
        dest: "{{ minecraft_dir }}/server.properties"
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_user }}"
        mode: '0644'
      notify: restart minecraft

    - name: Accept EULA
      copy:
        content: "eula=true\n"
        dest: "{{ minecraft_dir }}/eula.txt"
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_user }}"
        mode: '0644'

    - name: Create startup script
      template:
        src: start-minecraft.sh.j2
        dest: /opt/minecraft/scripts/start-minecraft.sh
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_user }}"
        mode: '0755'

    - name: Create systemd service file
      template:
        src: minecraft.service.j2
        dest: /etc/systemd/system/minecraft.service
        mode: '0644'
      notify:
        - reload systemd
        - restart minecraft

    - name: Enable and start minecraft service
      systemd:
        name: minecraft
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Check service status
      command: systemctl status minecraft
      register: service_status
      ignore_errors: yes

    - name: Display service status
      debug:
        var: service_status.stdout_lines

    - name: Check startup script logs
      shell: tail -20 /opt/minecraft/logs/minecraft-*.log 2>/dev/null || echo "No log files found"
      register: minecraft_logs
      ignore_errors: yes

    - name: Display minecraft logs
      debug:
        var: minecraft_logs.stdout_lines

    - name: Check java process
      shell: ps aux | grep java | grep -v grep
      register: java_process
      ignore_errors: yes

    - name: Display java process
      debug:
        var: java_process.stdout_lines

    - name: Check script permissions
      shell: ls -la /opt/minecraft/scripts/start-minecraft.sh
      register: script_perms
      ignore_errors: yes

    - name: Display script permissions
      debug:
        var: script_perms.stdout

    - name: Check if jar file exists
      shell: ls -la /opt/minecraft/server/minecraft_server.jar
      register: jar_file
      ignore_errors: yes

    - name: Display jar file info
      debug:
        var: jar_file.stdout

    - name: Check available memory
      shell: free -h
      register: memory_info
      ignore_errors: yes

    - name: Display memory info
      debug:
        var: memory_info.stdout_lines

    - name: Display connection information
      debug:
        msg:
          - "Minecraft server setup completed"
          - "Server IP: {{ ansible_default_ipv4.address }}"
          - "Server Port: {{ minecraft_port }}"
          - "Check the debug output above for any issues"
          - "If logs show errors, the server may need manual fixes"

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes

    - name: restart minecraft
      systemd:
        name: minecraft
        state: restarted